development:
  url: http://localhost:8069/xmlrpc         #the OpenERP XML/RPC server
  database: db               #the OpenERP database you want to connect to
  username: admin
  password: admin
  authenticate_ooorest: true
  global_context:
    'lang': en_US
